name: ${project.name}
main: ${mainclass}
version: ${project.version}
description: ${project.description}
author: ${author}
commands:
   MobileTools:
      description: Base command for admins.
      usage: /MobileTools
   MT:
      description: Base command for all the tools.
      usage: /MT